//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quickipedia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvisoryRead
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> AdvisoryID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
    }
}
