//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quickipedia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormOfPayment
    {
        public System.Guid ID { get; set; }
        public string ClientCode { get; set; }
        public string FOP { get; set; }
        public string IssuedCard { get; set; }
        public string CCLiquidationProcess { get; set; }
        public string TaxType { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string FOP_Others { get; set; }
        public string IssuedCard_Others { get; set; }
        public string CCLiquidation_Others { get; set; }
        public string MerchantFee { get; set; }
        public string Currency { get; set; }
        public string Other_Currency { get; set; }
    }
}
