//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quickipedia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableOfFees
    {
        public System.Guid ID { get; set; }
        public string ClientCode { get; set; }
        public string Category { get; set; }
        public Nullable<decimal> PHPTraditionalGDS { get; set; }
        public Nullable<decimal> PHPNonGDS { get; set; }
        public Nullable<decimal> PHPMice { get; set; }
        public Nullable<decimal> PHPOnline { get; set; }
        public Nullable<decimal> USDTraditionalGDS { get; set; }
        public Nullable<decimal> USDNonGDS { get; set; }
        public Nullable<decimal> USDMice { get; set; }
        public Nullable<decimal> USDOnline { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
